# Generated by Django 5.0.2 on 2024-03-22 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("last_updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
