# Generated by Django 5.0.2 on 2024-03-22 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="product_images/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_added_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
