# Generated by Django 5.0.2 on 2024-03-22 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocuments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                ("document", models.FileField(upload_to="user_documents/")),
                ("ipfs_id", models.CharField(max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
