# Generated by Django 4.0.1 on 2024-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_caretaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('change_profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('experience', models.FileField(blank=True, null=True, upload_to='experiences/')),
            ],
        ),
    ]
