# Generated by Django 4.0.1 on 2024-04-25 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile'),
        ('base', '0007_userrole'),
    ]

    operations = [
    ]
