# Generated by Django 4.0.1 on 2024-04-25 07:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('description', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
