# Generated by Django 4.1.9 on 2024-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_patientdocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdocument",
            name="file",
        ),
        migrations.AddField(
            model_name="patientdocument",
            name="file_gridfs_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
